config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'
  resources :bases
  resources :codes do
    member do
      get :merged
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base < ApplicationRecord
  mount_uploader :image, BaseImageUploader
  validates_processing_of :image
  validate :image_size_validation

private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/code.rb
class Code < ApplicationRecord
  mount_uploader :image, CodeImageUploader
  validates_processing_of :image
  validate :image_size_validation

private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
  before_action :set_basis, only: [:show, :edit, :update, :destroy]

  # GET /bases
  # GET /bases.json
  def index
    @bases = Base.all
  end

  # GET /bases/1
  # GET /bases/1.json
  def show
    redirect_to root_url
  end

  # GET /bases/new
  def new
    @basis = Base.new
  end

  # GET /bases/1/edit
  def edit
  end

  # POST /bases
  # POST /bases.json
  def create
    @basis = Base.new(basis_params)

    respond_to do |format|
      if @basis.save
        format.html { redirect_to @basis, notice: 'Base was successfully created.' }
        format.json { render :show, status: :created, location: @basis }
      else
        format.html { render :new }
        format.json { render json: @basis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bases/1
  # PATCH/PUT /bases/1.json
  def update
    respond_to do |format|
      if @basis.update(basis_params)
        format.html { redirect_to @basis, notice: 'Base was successfully updated.' }
        format.json { render :show, status: :ok, location: @basis }
      else
        format.html { render :edit }
        format.json { render json: @basis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bases/1
  # DELETE /bases/1.json
  def destroy
    @basis.destroy
    respond_to do |format|
      format.html { redirect_to bases_url, notice: 'Base was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basis
      @basis = Base.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basis_params
      params.require(:base).permit(:image)
    end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: [:show, :edit, :update, :destroy]

  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1
  # GET /codes/1.json

  def show
    # require "mini_magick"
    #
    # @codeimage = @code.image
    # croppedcode = @codeimage.cropped
    # compositecode = @codeimage.composite
    # base = Base.last.image
    #
    # newimage = MiniMagick::Image.open(croppedcode.url)
    # baseimage = MiniMagick::Image.open(base.url)
    # newimage.rotate("-10")
    #
    # newimage = baseimage.composite(newimage) do |c|
    #   c.compose("Darken")
    #   c.geometry("200x200+215+70")
    #   c.gravity("southeast")
    # end


    # newimage.write(@codeimage.composite.url)

    if Code.count > 1
      if Code.first.created_at < 7.days.ago
        Code.first.delete
      end
    end

    redirect_to root_url

  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1
  # PATCH/PUT /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code.destroy
    respond_to do |format|
      format.html { redirect_to codes_url, notice: 'Code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_params
      params.require(:code).permit(:image, :remove_image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @baseimage = Base.last
    @codeimage = Code.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bases/_form.html.erb
<%= form_with(model: basis, local: true) do |f| %>
  <% if basis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basis.errors.count, "error") %> prohibited this basis from being saved:</h2>

      <ul>
      <% basis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bases/edit.html.erb
<h1>Editing Basis</h1>

<%= render 'form', basis: @basis %>

<%= link_to 'Show', @basis %> |
<%= link_to 'Back', bases_path %>

app/views/bases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bases</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bases.each do |basis| %>
      <tr>
        <td><%= image_tag basis.image %></td>
        <td><%= link_to 'Show', basis %></td>
        <td><%= link_to 'Edit', edit_basis_path(basis) %></td>
        <td><%= link_to 'Destroy', basis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basis', new_basis_path %>

app/views/bases/new.html.erb
<h1>New Base Image</h1>

<%= render 'form', basis: @basis %>

<%= link_to 'Back', bases_path %>

app/views/bases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @basis.image %>
</p>
<p>
  <%= @basis.created_at.to_formatted_s(:long_ordinal) %>
</p>

<%= image_tag @basis.image.url %>

<%= link_to 'Edit', edit_basis_path(@basis) %> |
<%= link_to 'Back', bases_path %>

app/views/codes/_form.html.erb
<%= form_with(model: code, local: true) do |f| %>
  <% if code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
      <% if f.object.image? %>
        <%= image_tag f.object.image.thumb.url %>
        <%= f.label :remove_image %>
        <%= f.check_box :remove_image %>
      <% end %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Codes</h1>

<div class="row">

    <% @codes.each do |code| %>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <%= image_tag code.image.composite.url, class: "col-sm-12" %>
        <% timeago = (Time.now.to_date - code.created_at.to_date).to_i %>
        <% if timeago > 0 %>
          <td><%= timeago %> Days old. </td>
        <% elsif timeago == 0 %>
          <td>Uploaded Today.</td>
        <% else %>
          <td>Somehow uploaded in the future.</td>
        <% end %>
        <%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
</div>
<div class="row">
  <p></p>
</div>
<div class="row">
  <%= link_to 'Upload New QR Code', new_code_path, class: "btn btn-primary" %>
</div>

app/views/codes/merged.html.erb
<%= image_tag @code.composite.url %>

app/views/codes/new.html.erb
<h1>New Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @code.image %>
</p>
<p>
  <%= @code.created_at.to_formatted_s(:long_ordinal) %>
</p>
  <%# image_tag @code.image.url %>

<div class="row">
  <div class="col-sm-8">
    <%= image_tag @code.image.composite.url, class: "col-sm-12"%>
  </div>
</div>


<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BridgesAd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/main.html.erb
<h1>UW Bridges Ad Creator</h1>
<%= link_to "Upload new QR code", new_code_path, class: "btn btn-primary btn-xs" %>


<% if @baseimage == nil %>

  <p>You must first upload your base image.</p>

  <%= link_to "Upload base image", new_basis_path, class: "btn btn-primary" %>

<% else %>

  <% if Code.any? %>

  <h3>Current Ad Image</h3>

  <div class="row qr-images">
      <%= image_tag @codeimage.image.composite.url, class: "col-sm-12 col-md-6" %>
      <p class="col-sm-12 col-md-6">
        <% timeago = (Time.now.to_date - @codeimage.created_at.to_date).to_i %>
        <strong>
        <% if timeago > 6 %>
          <h2 style="color: red;">
            <%= timeago %> Days old.
          </h2>
          <p>It's time to upload a new image. This one has expired or will soon.</p>
          <%= link_to "Upload new QR now!", new_code_path, class: "btn btn-primary" %>
        <% else %>
          <h2>
            <%= timeago %> days old. Will expire in less than <%= (7-timeago).to_s %> days.
          </h2>
        <% end %>
        </strong>
      </p>
  </div>

  <% else %>

  <div class="row">
    <%= image_tag @baseimage.image.url, class: "col-sm-12 col-md-6" %>
  </div>

  <div class="row">
    <p class="col-sm-12 col-md-6">Base image successfully loaded. Upload your WeChat QR code image.</p>
  </div>

  <%= link_to "Upload new QR Code", new_code_path, class: "btn btn-primary" %>

  <% end %>

<% end %>